package com.ioabsoftware.gameraven.networking;

public enum NetDesc {
    UNSPECIFIED, MODHIST,
    VERIFY_ACCOUNT_S1, VERIFY_ACCOUNT_S2,
    LOGIN_S1, LOGIN_S2,
    BOARD_JUMPER, GAME_SEARCH, BOARD_LIST, AMP_LIST, TRACKED_TOPICS, BOARD, TOPIC, MESSAGE_DETAIL, USER_DETAIL,
    PM_INBOX, PM_OUTBOX, PM_INBOX_DETAIL, PM_OUTBOX_DETAIL, PM_SEND_S1, PM_SEND_S2,
    MSG_MARK, MSG_DELETE, TOPIC_CLOSE,
    USER_TAG,
    MSG_POST_S1, MSG_POST_S3, // no step 2 as all are quick-posted now
    TOPIC_POST_S1, TOPIC_POST_S3, // no step 2 as all are quick-posted now
    EDIT_MSG,
    NOTIFS_PAGE, NOTIFS_CLEAR
}
